Created a separate class for all phidget bridge related functions, wi…
jhu-asco/esc_closed_loop_force_control pull request #1
Opened 2017-07-10 21:37 UTC by jchung55

Please review these two files: phidget_bridge, test_phidget_bridge

2017-07-10 22:17 UTC, garimellagowtham requested changes
Looking Good!

2017-07-10 22:17 UTC, garimellagowtham commented on phidget_bridge.py
> +class PhidgetBridge:
Add description about the class.
Something like wrapper class to read in force from Phidgets voltage bridge

2017-07-10 22:17 UTC, garimellagowtham commented on phidget_bridge.py
> +        self.connected_status = False
Add comments about member variables

2017-07-10 22:17 UTC, garimellagowtham commented on test_phidget_bridge.py
> +phidget_bridge.waitingForConnection(timeout = 5000)
After this line check phidget is connected. If not exit

2017-07-10 22:17 UTC, garimellagowtham commented on test_phidget_bridge.py
> +time_off = 0.1
No comment here?
"Time interval between force data collection"

2017-07-10 22:17 UTC, garimellagowtham commented on test_phidget_bridge.py
> +import time
Add a few comment lines on what this file does. Something like:
" Testing Phidget Bridge! Instantiate and collect force data from the load cell.

  Author: Joseph Chung
  Email:
"

2017-07-11 17:40 UTC, msheckells commented
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[phidget_bridge.py, line 24 at r1](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1#-KomhmZeuzzCrTFGrO-N:-KomhmZeuzzCrTFGrO-O:b-rypyev) ([raw file](https://github.com/jhu-asco/esc_closed_loop_force_control/blob/99dcbeac8754025de836ada597e0b923506df5cd/phidget_bridge.py#L24)):*
> ```Python
>         self.ch.setOnVoltageRatioChangeHandler(self.voltageRatioChangeHandler)
>     
>     # Function to wait for a connection to the PhidgetBridge    
> ```

In general, function documentation should describe the function parameters as well, e.g.

timeout Time to wait for connection in milliseconds

---

*[test_phidget_bridge.py, line 13 at r1](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1#-Komj1VMTorEsRfFykmu:-Komj1VMTorEsRfFykmv:b-at231w) ([raw file](https://github.com/jhu-asco/esc_closed_loop_force_control/blob/99dcbeac8754025de836ada597e0b923506df5cd/test_phidget_bridge.py#L13)):*
> ```Python
> phidget_bridge.waitingForConnection(timeout = 5000)
> # While iterating 10 times, prints the force and sleeps for a specified time
> while i < 10:
> ```

Use `for i in range(10):` instead of a while loop with  a counter.  It is cleaner in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1)*
<!-- Sent from Reviewable.io -->

2017-07-12 22:46 UTC, garimellagowtham approved these changes

2017-07-12 22:52 UTC, garimellagowtham commented
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[phidget_bridge.py, line 97 at r2](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1#-Kosz8uadWHyAXNYl0F4:-Kosz8uadWHyAXNYl0F5:b62nn0k) ([raw file](https://github.com/jhu-asco/esc_closed_loop_force_control/blob/2a90546757f939b6dc927f16d371d97ff220848f/phidget_bridge.py#L97)):*
> ```Python
>     def close(self):
>         self.ch.close()
>         
> ```

Remove spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1)*
<!-- Sent from Reviewable.io -->

2017-07-13 02:41 UTC, garimellagowtham commented
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test_phidget_bridge.py, line 30 at r3](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1#-KotofJCcMvwyLDb9M1D:-KotofJCcMvwyLDb9M1E:b3f5t1q) ([raw file](https://github.com/jhu-asco/esc_closed_loop_force_control/blob/1504db7d2ac21c4bb1e11499082ca99212de0467/test_phidget_bridge.py#L30)):*
> ```Python
>     print(phidget_bridge.getForce())
>     time.sleep(time_off)
>     i += 1
> ```

You do not need to increase i in this for loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1)*
<!-- Sent from Reviewable.io -->

2017-07-13 14:00 UTC, msheckells commented
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1)*
<!-- Sent from Reviewable.io -->

2017-07-13 15:12 UTC, garimellagowtham commented
Reviewed 1 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1)*
<!-- Sent from Reviewable.io -->

2017-07-13 19:05 UTC, msheckells commented
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/1)*
<!-- Sent from Reviewable.io -->

2017-07-13 20:04 UTC, merged