Arduino branch
jhu-asco/esc_closed_loop_force_control pull request #2
Opened 2017-07-10 22:58 UTC by jchung55

Please review arduino_communication and test_arduino_communication

2017-07-10 23:45 UTC, garimellagowtham requested changes

2017-07-10 23:45 UTC, garimellagowtham commented on phidget_bridge.py
> +from Phidget22.Devices.VoltageRatioInput import VoltageRatioInput
remove this file from this branch

2017-07-10 23:45 UTC, garimellagowtham commented on test_phidget_bridge.py
> +import time
Remove this file from this branch

2017-07-10 23:45 UTC, garimellagowtham commented on test_arduino_commmunication.py
> +percentage_array = np.linspace(6,55, 5)
Add space after comma

2017-07-10 23:46 UTC, garimellagowtham requested changes

2017-07-10 23:46 UTC, garimellagowtham commented on arduino_communication.py
> +    def sendMotorCommandtoArduino(self, percentage = 0):
Rename: `sendMotorCommandToArudino`

2017-07-10 23:46 UTC, garimellagowtham commented on arduino_communication.py
> +
Add comments to class and functions

2017-07-10 23:46 UTC, garimellagowtham commented on arduino_communication.py
> +        self.port = 'com6'
Take the port and baud rate as arguments to the constructor as in `__init__(self, port='com6', baud_rate=9600)`
You do not have to store the baud rate and com port one you merge the `connectingWithArduino` function with the constructor

2017-07-10 23:46 UTC, garimellagowtham commented on arduino_communication.py
> +    def connectingWithArduino(self, timeout = 2):
We do not need this function Merge this with constructor

2017-07-10 23:46 UTC, garimellagowtham commented on test_arduino_commmunication.py
> +arduino_communication.closeArduino()
Add a new line at end of file

2017-07-11 17:47 UTC, msheckells commented
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[arduino_communication.py, line 8 at r1](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/2#-KomjhXF_fd5-iq2Rd4b:-KomjhXGQQBwYM70z33x:btup4ky) ([raw file](https://github.com/jhu-asco/esc_closed_loop_force_control/blob/472d0f77d31ec226f1073c515e8eeeb0ef9906d9/arduino_communication.py#L8)):*
> ```Python
>     
>     def __init__(self):
>         self.voltage_scale = (5.0/1023.0)*10.1
> ```

Would be good to store special numbers in their own variables with descriptive names, e.g. `self.adc_conversion_factor = 5.0/1023.0`.

At the very least add a comment about what the numbers above correspond to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/esc_closed_loop_force_control/2)*
<!-- Sent from Reviewable.io -->

2017-07-12 22:38 UTC, garimellagowtham approved these changes

2017-07-12 22:39 UTC, merged